### ISSUE TITLE
Improvements in relation to original repo?

### ISSUE THREAD

**Issue by haschdl** [28Pollux28/pngj#1]
hello @28Pollux28 ! it looks like your fork is the most updated fork from the original https://github.com/leonbloy/pngj 
I would like to try writing metadata to PNG images generated from Processing, and I'm inclined to use your version as it seems to have received more updates. Would you be able to give a summary of the improvements you made to the original library, and if you know of any remaining bugs or things to watch out for?

**Comment by 28Pollux28** [comment]
My fork was created to fix an issue in alexdupre's repo. I haven't worked at all on this repo
